backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "landingPage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: "hidden",
              default: "landing-page",
            }
          - {
              label: "Landing Page",
              name: landingPage,
              widget: object,
              fields:
                [
                  { label: "Title", name: title, widget: string },
                  {
                    label: "Cards",
                    name: "cards",
                    widget: list,
                    fields:
                      [
                        {
                          label: "Title",
                          name: "title",
                          widget: string,
                          required: true,
                        },
                        {
                          label: "Description",
                          name: "description",
                          widget: string,
                          required: true,
                        },
                        {
                          label: "Title",
                          name: "title",
                          widget: string,
                          required: true,
                        },
                        {
                          label: "To",
                          name: "to",
                          widget: "string",
                          required: true,
                        },
                        {
                          label: "Image",
                          name: "img",
                          widget: image,
                          required: true,
                        },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About Page"
        name: "aboutPage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: "hidden",
              default: "about",
            }
          - {
              label: "About Page",
              name: aboutPage,
              widget: object,
              fields:
                [
                  { label: "Title", name: title, widget: string },
                  { label: "Description", name: description, widget: string },
                  {
                    label: "Contact Slogan",
                    name: contactSlogan,
                    widget: string,
                  },
                  {
                    label: "Passages",
                    name: "sections",
                    widget: list,
                    fields:
                      [
                        {
                          label: "Title",
                          name: "title",
                          widget: string,
                          required: true,
                        },
                        {
                          label: "Body",
                          name: "body",
                          widget: "string",
                          required: true,
                        },
                      ],
                  },
                ],
            }
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "contactPage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: "hidden",
              default: "contact",
            }
          - {
              label: "Contact Page",
              name: contactPage,
              widget: object,
              fields:
                [
                  { label: "Title", name: title, widget: string },
                  { label: "Description", name: description, widget: string },
                  {
                    label: "Contact Form",
                    name: "contactForm",
                    widget: object,
                    fields:
                      [
                        {
                          label: "Telephone",
                          name: "telephone",
                          widget: string,
                          required: true,
                        },
                        {
                          label: "Email",
                          name: "email",
                          widget: string,
                          required: true,
                        },
                        {
                          label: "Address",
                          name: "address",
                          widget: string,
                          required: true,
                        },
                        {
                          label: "Subtitle",
                          name: "subtitle",
                          widget: string,
                          required: true,
                        },
                        {
                          label: "links",
                          name: "links",
                          widget: object,
                          fields:
                            [
                              {
                                label: "Facebook",
                                name: "facebook",
                                widget: string,
                                required: true,
                              },
                              {
                                label: "Twitter",
                                name: "twitter",
                                widget: string,
                                required: true,
                              },
                              {
                                label: "Dribbble",
                                name: "dribbble",
                                widget: string,
                                required: true,
                              },
                            ],
                        },
                      ],
                  },
                ],
            }
      - file: "src/pages/project/index.md"
        label: "Project Page"
        name: "projectPage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: "hidden",
              default: "project",
            }
          - {
              label: "Project Page",
              name: projectPage,
              widget: object,
              fields:
                [
                  { label: "Title", name: title, widget: string },
                  { label: "Description", name: description, widget: string },
                  { label: "Footer", name: footer, widget: string },
                  {
                    label: "Images",
                    name: "images",
                    widget: list,
                    fields:
                      [
                        {
                          label: "Image",
                          name: "img",
                          widget: image,
                          required: true,
                        },
                      ],
                  },
                ],
            }
      - file: "src/pages/services/index.md"
        label: "Services Page"
        name: "servicesPage"
        fields:
          - {
              label: "Template Key",
              name: templateKey,
              widget: "hidden",
              default: "services",
            }
          - {
              label: "Services Page",
              name: servicesPage,
              widget: object,
              fields:
                [
                  { label: "Title", name: title, widget: string },
                  { label: "Description", name: description, widget: string },
                  {
                    label: "Services Cards",
                    name: "servicesCards",
                    widget: list,
                    fields:
                      [
                        { label: "Title", name: title, widget: string },
                        { label: "Body", name: body, widget: string },
                        {
                          label: "Image",
                          name: "image",
                          widget: image,
                          required: true,
                        },
                        {
                          label: "Link",
                          name: "link",
                          widget: object,
                          fields:
                            [
                              { label: "To", name: to, widget: string },
                              {
                                label: "Button Text",
                                name: text,
                                widget: string,
                              },
                            ],
                        },
                      ],
                  },
                ],
            }
